### ISSUE TITLE
Create a GUI for this game

### ISSUE THREAD

**Issue by savva-k** [savva-k/checkers-server#1]
For now it is a console version.

**Comment by ironsigma** [comment]
I'd like to build a GUI using Java Swing, let me know what you think.

**Comment by savva-k** [comment]
> I'd like to build a GUI using Java Swing, let me know what you think.

@ironsigma, it's yours! I like it.

**Comment by savva-k** [comment]
@ironsigma thank you for the contribution, it's merged and I've added you to contributors section.
